# Generated by Django 3.2.8 on 2021-10-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211013_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
